# if your imports fail, try this:
#export PYTHONPATH=$PYTHONPATH:$(pwd)

## This is a simple makefile to fasten Musig2 compilation and testing


#compile Cairo and Sage and Compare Results
test_bls12_381:
	sage common/arithmetic/curves/bls12_381.sage
test_ecdaa:
	sage ECDAA/tests/test_ECDAA.sage


